version: "3"
services:

  amqp:
    container_name: amqp
    image: rabbitmq:3.13-rc
    ports:
      - "5672:5672"
      - "8181:15672"
    volumes:
      - type: bind
        source: ./rabbitmq-enabled-plugins
        target: /etc/rabbitmq/enabled_plugins
      - type: bind
        source: ./rabbitmq.config
        target: /etc/rabbitmq/rabbitmq.config
      - type: bind
        source: ./rabbitmq-defs.json
        target: /etc/rabbitmq/rabbitmq-defs.json
    networks:
      - rabbitmq_go_net

  streamingflow4j-rabbitmq:
    container_name: streamingflow4j-rabbitmq
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: streamingflow4j-rabbitmq:latest
    ports:
      - "8081:8081"
    environment:
      RABBIT_HOST: amqp
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      QUEUE_DATA: si.test.queue
      QUEUE_RULE: si.ceprule.queue
      RABBIT_VIRTUAL_HOST: /
      RABBIT_PORT: 5672
      JAR_NAME: StreamingFlow4JRabbitMQ-0.0.1-SNAPSHOT.jar
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    name: localNet
    driver: bridge