version: "3"
services:

  amqp:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "8080:15672"
    networks:
      - rabbitmq_go_net

  middleware-rabbitmq:
    container_name: middleware-rabbitmq
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: middleware-rabbitmq:latest
    environment:
      RABBIT_HOST: amqp
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      QUEUE_DATA: si.test.queue
      QUEUE_RULE: si.ceprule.queue
      JAR_NAME: ServiceMiddlewareRabbitMQ-0.0.1-SNAPSHOT.jar
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    name: localNet
    driver: bridge