version: "3"
services:

  consumer-rabbitmq:
    container_name: consumer-rabbitmq
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: consumer-rabbitmq:latest
    ports:
      - "8082:8082"
    environment:
      environment:
      RABBIT_HOST: amqp
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      RABBIT_VIRTUAL_HOST: /
      RABBIT_PORT: 5672
      KAFKA_CONSUMER_QUEUE: si.cep.queue
      JAR_NAME: SpringBootRabbitMQConsumer-0.0.1.jar
    networks:
      - rabbitmq_go_net
    
networks:
  rabbitmq_go_net:
    external:
      name: localNet