version: "3"
services:

  endpoint-rest-rabbit:
    container_name: consumer-endpoint-rabbit
    build:
      context: ./target
      dockerfile: ./Dockerfile
    image: rest-endpoint-rabbit:latest
    ports:
      - "8082:8082"
    environment:
      RABBIT_HOST: amqp
      RABBIT_USERNAME: guest
      RABBIT_PASSWORD: guest
      QUEUE_DATA: si.test.queue
      QUEUE_RULE: si.ceprule.queue
      JAR_NAME: SpringBootRabbitMQConsumer-0.0.1.jar
    networks:
      - rabbitmq_go_net
    
networks:
  rabbitmq_go_net:
    external:
      name: localNet